version: "3"

services:

  db:
    image: postgres
    restart: always
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - docker.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
