version: "3"

services:

  app:
    build: ../.
    env_file:
      - ../.env
    container_name: task_1_app
    ports:
      - "9999:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: question_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data_task_1:/var/lib/postgresql/data

volumes:
  db_data_task_1:
